# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /fun

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
  #  resources:
  #    add-mappings: false

  #配置kafka
  kafka:
    bootstrap-servers: 192.168.101.10:9092  #集群地址，以逗号分隔的主机：端口对列表
    consumer:
      group-id: fun               #指定默认消费者组名字（group id）
      enable-auto-commit: false   #是否让kafka去自动提交offset，默认值为true，设为false则让Spring（代理）自动提交offset
  #QQ邮箱邮件smtp服务配置（需要把SMTP协议更换为SMTPS协议，否则频率高就会被误判为垃圾邮件而封禁）
  mail:
    host: smtp.qq.com
    username: ***
    password: ***
    test-connection: true
    port: 465
    properties:
      mail.smtp.auth: true                                            #开启认证
      mail.smtp.timeout: 1000                                         #设置链接超时
      mail.smtp.port: 465                                             #使用SMTPS协议465端口
      mail.smtp.socketFactory.port: 465                               #使用SMTPS协议465端口
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory   #SSL证书Socket工厂


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lsd.fun.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

fun:
  redis:
    keyPrefix:
      dictionary: fun:dictionary
      mail-captcha: fun:mail_captcha
      cart: fun:cart
      etl: fun:etl
  elasticsearch:
    node-list: 127.0.0.1:9200
  max-suggest: 5
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    secret: *** # 加密密钥
    expire: 604800  # token有效时长，7天，单位秒
    header: token
  auth:
    admin:
      username: admin
      default-password: admin
      salt: ***
      enabled: true
  qiniu:
    enable: true
    accessKey: ***
    secretKey: ***
    bucket: fun-test
    cdnPrefix: cdn
    hostPrefix: ***   #外链默认域名
    # 允许上传的文件格式
    allowTypes:
      - .bmp
      - .jpg
      - .jpeg
      - .gif
      - .png
    avatar-path: avatar
    image-path: image
    video-path: video
    other-path: other

#百度地图 API Key
baidu-map:
  apiKey: ***
  geocoderApiPrefix: ***
  poi:
    geotableId: ***
    createUrl: http://api.map.baidu.com/geodata/v3/poi/create
    queryUrl: http://api.map.baidu.com/geodata/v3/poi/list
    updateUrl: http://api.map.baidu.com/geodata/v3/poi/update
    deleteUrl: http://api.map.baidu.com/geodata/v3/poi/delete

#spark:
#  master: spark://spark-master:7077
